SELECT
/*
  ai1.ANIMAL_ID,
  ai1.ANIMAL_TYPE,
  ai1.DATETIME,
  ai1.INTAKE_CONDITION,
  ai1.NAME,
  ai1.SEX_UPON_INTAKE
*/
  ai1.DATETIME AS 시간
FROM ANIMAL_INS AS ai1
ORDER BY ai1.DATETIME DESC
LIMIT 1